# yaml aks pipeline

trigger:
- main

pool:
 vmImage: "ubuntu-latest"

 # s2 j2 s
 stages:
   - stage:
     displayName: aks_deployment
     jobs:
       - job
          displayName:microservices_deployment
          steps:

            - task: kubernetesManifest@1
              inputs:
                action: 'deploy'
                connectionType: 'kubernetesServiceConnection'
                kubernetesServiceConnection: 'aks-conn'
                namespace: 'class-ns'
                manifests: 'release/kubernetes-manifests.yaml'
