# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: "ubantu-latest"

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: microservices_deployment
    pool:
      vmImage: ubuntu-latest
    steps:
      task: Docker@2
      displayName: Build an image
      inputs:
        action: "deploy"
        command: build
        dockerfile: 'dployment.yaml'
        tags: |
          $(tag)
